# -*- coding: utf-8 -*-
"""
/***************************************************************************
 poligono_coordenadas
                                 A QGIS plugin
 carga un archivo con coordenadas y genera el poligono 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-05
        copyright            : (C) 2021 by viviana
        email                : vivianaandrea26@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load poligono_coordenadas class from file poligono_coordenadas.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Pol_coord import poligono_coordenadas
    return poligono_coordenadas(iface)
